ip_interfaces:
  - inteface: ether2
    address: 192.172.17.1/24

  - interface: ether3
    address: 192.168.40.1/24

dhcp_servers:
  - interface: ether2
    pool_name: iot_pool
    pool_range: 192.172.17.10-192.172.17.50
    network: 192.172.17.0/24
    gateway: 192.172.17.1
    dns: 8.8.8.8

  - interface: ether3
    pool_name: dhcp_pool2
    pool_range: 192.168.40.10-192.168.40.100
    network: 192.168.40.0/24
    gateway: 192.168.40.1
    dns: 8.8.8.8


