- name: Cek versi RouterOS MikroTik
  hosts: mikrotik
  gather_facts: no

  tasks:
    - name: Ambil informasi RouterOS
      community.routeros.command:
        commands:
          - /system resource print
      register: output

    - name: Tampilkan output RouterOS
      debug:
        var: output.stdout_lines
